services:
  - type: web
    name: cookly
    runtime: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cookly-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: FLASK_ENV
        value: production
      - key: DISABLE_MODEL
        value: false

databases:
  - name: cookly-db
    region: frankfurt
    plan: free
    databaseName: cookly
    user: cookly_user
